elasticsearch.host: localhost
elasticsearch.port: 9300
elasticsearch.cluster: elasticsearch
elasticsearch.alias: facilities
elasticsearch.doctype: facility

job.lis.reader.query: select
                            f.fac_nbr as "id",
                            ft.tbl_fac_type_desc as "type",
                            f.fac_name as "name",
                            f.fac_licensee_name as "licenseeName",
                            f.fac_do_eval_code as "assignedWorker",
                            dc.do_name as "districtOffice",
                            f.fac_nbr as "licenseNumber",

                            f.fac_mail_street_addr as "streetAddress",
                            f.fac_mail_city as "city",
                            f.fac_mail_state as "stateCodeType",
                            f.fac_mail_zip_code as "zipCode",
                            '' as streetNumber,
                            '' as zipSuffixCode,

                            f.fac_res_street_addr as "residentialStreetAddress",
                            f.fac_res_city as "residentialCity",
                            f.fac_res_state as "residentialState",
                            f.fac_res_zip_code as "residentialZip",

                            co.tbl_co_desc as "county",
                            f.fac_phone_nbr as "primaryPhoneNumber",
                            '' as "altPhoneNumber",
                            fs.tbl_fac_status_desc as "status",
                            '' as "licenseStatus",
                            '' as "streetName",

                            f.fac_licensee_type as "licenseeType",
                            f.fac_lic_eff_date as "licenseEffectiveDate",
                            f.fac_last_visit_date as "lastVisitDate",
                            f.fac_last_visit_reason as "lastVisitReason",
                            f.fac_email_address as "emailAddress",
                            f.fac_capacity as "capacity",
                            f.fac_orig_appl_rec_date as "originalApplicationReceivedDate"
                          from
                            lis_fac_file f,
                            lis_do_file dc,
                            lis_table_file ft,
                            lis_table_file fs,
                            lis_table_file co
                          where f.fac_do_nbr = dc.do_nbr
                                and f.fac_type = ft.TBL_FAC_TYPE_CODE
                                and ft.TBL_FAC_TYPE_CODE is not null
                                and f.fac_status = fs.tbl_fac_status_code
                                and fs.tbl_fac_status_code is not null
                                and f.fac_co_nbr = co.tbl_co_nbr
                                and co.tbl_co_nbr is not null;