elasticsearch.host: elasticsearch.preint.cwds.io
elasticsearch.port: 9300
elasticsearch.cluster: es-preint
# elasticsearch.alias: people_05-17-2017_09-55
elasticsearch.alias: people
elasticsearch.doctype: person
