elasticsearch:
  elasticsearch.additional.nodes:
  - localhost:9300
  - localhost:9300

  elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
  elasticsearch.alias: ${ELASTIC_SEARCH_AUDIT_EVENTS_ALIAS:-auditevents}
  elasticsearch.doctype: ${ELASTIC_SEARCH_AUDIT_EVENT_DOCTYPE:-auditevent}
  elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
  elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}
  #
  elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
  elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}
