batchSize: 500
elasticSearchBulkSize: 500
readerThreadsCount: 1

elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}

elasticsearch.additional.nodes:
  - localhost:9300
  - localhost:9300

elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch_DimaS}
elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-users}
elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-user}
#
elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

perryApiUrl: ${PERRY_URL:-http://localhost:18080/perry/idm/users}
perryApiUser: ${PERRY_USER:-user}
perryApiPassword: ${PERRY_PASS:-pass}
jerseyClientConnectTimeout: ${CONNECT_TIMEOUT:-20000}
jerseyClientReadTimeout: ${READ_TIMEOUT:-60000}