elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}
elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-rfa1aforms}
elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-rfa1aform}
#
elasticsearch.index.settings: ${ELASTIC_SEARCH_INDEX_SETTINGS:-config/cals/rfa/rfa.settings.json}
elasticsearch.document.mapping: ${ELASTIC_SEARCH_DOCUMENT_MAPPING:-config/cals/rfa/rfa.mapping.json}
#
elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

calsnsDataSourceFactory:
  properties:
      hibernate.current_session_context_class: thread
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.connection.username: ${DB_NS_USER:-postgres_data}
      hibernate.connection.password: ${DB_NS_PASSWORD:-postgres_data}
      hibernate.connection.url: ${DB_NS_JDBC_URL:-jdbc:postgresql://192.168.99.100:32770/?currentSchema=calsns}
      hibernate.connection.pool_size: ${DB_NS_CP_MAX_SIZE:-8}
      hibernate.show_sql: false

